import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Sparkles, Heart, Star, Sun, Moon, ChevronDown, ChevronRight, X, Menu, Bookmark, Download, Link, Share2, LockKeyhole, Check, Flower2, Coffee, WandSparkles } from 'lucide-react';
import { makeFortune, makeCompatibility, validatePerson, seoulDate, publicCard, parseSharedCard, savedResult, makeSajuFromResult } from './fortune.js';
import { ENGINE, lunarMonthDays, stemInfo } from './manse.js';
import { PremiumReport, ReportPreview, MatchScenes } from './PremiumReport.jsx';
import {GuardianCharm,GuardianShowcase} from './GuardianCharm.jsx';
import {CharmCollection} from './CharmCollection.jsx';
import {AccountPanel,useAccountVault} from './Account.jsx';
import {ManualPreview} from './ManualCard.jsx';
import {makeReport} from './report.js';
import './styles.css';
import {createCard} from './resultCard.js';
import './result-next.css';

const blankPerson = () => ({ name: '', birth: '', time: '', unknown: false, calendar: 'solar', leap: false, boundary: 'midnight' });
function Hamster({ size = 42 }) { return <svg width={size} height={size} viewBox="0 0 72 72" aria-hidden="true"><ellipse cx="36" cy="42" rx="29" ry="25" fill="#f0c799"/><circle cx="16" cy="20" r="12" fill="#efc495"/><circle cx="56" cy="20" r="12" fill="#efc495"/><circle cx="16" cy="20" r="7" fill="#efada6"/><circle cx="56" cy="20" r="7" fill="#efada6"/><ellipse cx="36" cy="43" rx="25" ry="23" fill="#f8ddae"/><ellipse cx="36" cy="50" rx="20" ry="15" fill="#fff3de"/><circle cx="26" cy="39" r="3" fill="#5e4639"/><circle cx="46" cy="39" r="3" fill="#5e4639"/><ellipse cx="17" cy="47" rx="6" ry="4" fill="#efb0a4"/><ellipse cx="55" cy="47" rx="6" ry="4" fill="#efb0a4"/><path d="M32 47Q36 52 40 47M36 47V51" stroke="#795342" strokeWidth="2" fill="none" strokeLinecap="round"/><path d="M20 26L36 4 50 26Z" fill="#b0a0ce"/><path d="M15 27Q36 19 56 27" stroke="#aa95c8" strokeWidth="7" strokeLinecap="round"/><path d="m36 11 1.5 4.5 4.5.2-3.5 3 1 4-3.5-2.5-3.5 2.5 1-4-3.5-3 4.5-.2z" fill="#fff0b3"/></svg>; }
function MiniArt({ type }) { return <div className={`mini-art ${type}`} aria-hidden="true">{type==='sun' ? <><Sun size={65} strokeWidth={1.4}/><span className="art-cloud">☁</span><span className="art-star">✧</span></> : type==='orb' ? <><div className="orb"><Sparkles size={30}/></div><div className="orb-base"/><span className="art-star">✧</span></> : <><Heart className="heart-one" size={60} fill="currentColor" strokeWidth={1}/><Heart className="heart-two" size={43} fill="currentColor" strokeWidth={1}/><span className="art-star">✧</span></>}</div>; }
function BirthFields({birth,onChange,prefix,calendar,leap}) {
  const [year='',month='',day='']=(birth || '').split('-');
  const maxFor=(y,m)=>calendar==='lunar'?(lunarMonthDays(y.length===4?Number(y):null,Number(m),leap)||30):new Date(y.length===4?Number(y):2000,Number(m),0).getDate();
  const daysInMonth=month?maxFor(year,month):(calendar==='lunar'?30:31);
  useEffect(()=>{if(Number(day)>daysInMonth)onChange([year,month,''].join('-'));},[daysInMonth,day,year,month,onChange]);
  function change(part,value){const next=[year,month,day];next[part]=value;if(part!==2 && next[1] && next[2] && (part===1 || next[0].length===4)){const max=maxFor(next[0],next[1]);if(Number(next[2])>max)next[2]='';}onChange(next.join('-'));}
  return <><div className="birth-fields" role="group" aria-label="생년월일 입력"><div className="year-input"><input id={`${prefix}-year`} aria-label="태어난 연도" type="text" inputMode="numeric" autoComplete="bday-year" required maxLength={4} pattern="[0-9]{4}" placeholder="연도" value={year} onChange={e=>change(0,e.target.value.replace(/\D/g,''))}/><span aria-hidden="true">년</span></div><div className="birth-select"><select aria-label="태어난 월" autoComplete="bday-month" required value={month} onChange={e=>change(1,e.target.value)}><option value="" disabled>월 선택</option>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{i+1}월</option>)}</select><ChevronDown size={14} aria-hidden="true"/></div><div className="birth-select"><select aria-label="태어난 일" autoComplete="bday-day" required value={day} onChange={e=>change(2,e.target.value)}><option value="" disabled>일 선택</option>{Array.from({length:daysInMonth},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{i+1}일</option>)}</select><ChevronDown size={14} aria-hidden="true"/></div></div><small className="birth-help">연도는 숫자로 입력하고, 월과 일을 골라주세요.</small></>;
}
function TimeFields({time,onChange,unknown,prefix}) {
  const [hour24='',minute='']=(time || '').split(':');
  const [period,setPeriod]=useState(Number(hour24)>=12?'pm':'am');
  useEffect(()=>{if(hour24!=='')setPeriod(Number(hour24)>=12?'pm':'am');},[hour24]);
  const hour=hour24===''?'':String(Number(hour24)%12 || 12).padStart(2,'0');
  function changePeriod(next){setPeriod(next);if(hour!=='')onChange(`${String(Number(hour)%12+(next==='pm'?12:0)).padStart(2,'0')}:${minute}`);}
  function changeHour(next){onChange(`${String(Number(next)%12+(period==='pm'?12:0)).padStart(2,'0')}:${minute}`);}
  return <><fieldset className="time-fields" disabled={unknown} aria-label="태어난 시간 입력"><div className="birth-select"><select id={`${prefix}-period`} aria-label="오전 또는 오후" value={period} onChange={e=>changePeriod(e.target.value)}><option value="am">오전</option><option value="pm">오후</option></select><ChevronDown size={14} aria-hidden="true"/></div><div className="birth-select"><select aria-label="태어난 시" required={!unknown} value={hour} onChange={e=>changeHour(e.target.value)}><option value="" disabled>시 선택</option>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{i+1}시</option>)}</select><ChevronDown size={14} aria-hidden="true"/></div><div className="birth-select"><select aria-label="태어난 분" required={!unknown} value={minute} onChange={e=>onChange(`${hour24}:${e.target.value}`)}><option value="" disabled>분 선택</option>{Array.from({length:60},(_,i)=><option key={i} value={String(i).padStart(2,'0')}>{String(i).padStart(2,'0')}분</option>)}</select><ChevronDown size={14} aria-hidden="true"/></div></fieldset><small className={`birth-help time-help ${unknown?'unknown-help':''}`}>{unknown?'태어난 시간을 몰라도 괜찮아요. 입력 없이 볼 수 있어요.':hour==='12'?'오전 12시는 자정, 오후 12시는 낮 12시예요.':'한국 표준시 기준으로 오전·오후, 시와 분을 골라주세요.'}</small></>;
}
function PersonFields({ value, setValue, prefix = 'me' }) { const update=(k,v)=>setValue({...value,[k]:v}); return <div className="person-fields">
  <label htmlFor={`${prefix}-name`}>이름 또는 닉네임<input id={`${prefix}-name`} required maxLength={16} autoComplete="off" placeholder="어떻게 불러드릴까요?" value={value.name} onChange={e=>update('name',e.target.value)}/></label>
  <div className="field-heading"><label htmlFor={`${prefix}-year`}>생년월일</label><div className="segmented" aria-label="달력 종류">{[['solar','양력'],['lunar','음력']].map(([v,t])=><button key={v} type="button" aria-pressed={value.calendar===v} onClick={()=>update('calendar',v)} className={value.calendar===v?'active':''}>{t}</button>)}</div></div>
  <BirthFields prefix={prefix} calendar={value.calendar} leap={value.leap} birth={value.birth} onChange={v=>update('birth',v)}/>
  {value.calendar==='lunar' && <label className="checkbox-label lunar-leap"><input type="checkbox" checked={!!value.leap} onChange={e=>update('leap',e.target.checked)}/>윤달에 태어났어요 <small>평달은 체크하지 않아요</small></label>}
  <div className="field-heading time-heading"><label htmlFor={`${prefix}-period`}>태어난 시간</label><label className="checkbox-label"><input type="checkbox" checked={value.unknown} onChange={e=>update('unknown',e.target.checked)}/>시간 모름</label></div>
  <TimeFields prefix={prefix} time={value.time} unknown={value.unknown} onChange={v=>update('time',v)}/>
  
  <details className="calculation-options"><summary>사주 계산 기준 <ChevronDown size={14}/></summary><label>일주가 바뀌는 시각<select aria-label="일주 날짜 경계" value={value.boundary || 'midnight'} onChange={e=>update('boundary',e.target.value)}><option value="midnight">자정 00:00 기준</option><option value="zi">밤 23:00 자시 기준</option></select></label><p>한국 표준시(UTC+9)로 계산해요. 해외 출생, 과거 표준시·서머타임은 표준시로 보정해 입력해주세요. 출생지에 따른 태양시 보정은 적용하지 않아요.</p></details>
  </div>; }
function ChartPanel({chart,title}) {
  if(!chart)return null;
  const countLabel=e=>e.min===e.max?String(e.min):`${e.min}~${e.max}`;
  return <section className="chart-panel"><div className="chart-heading"><h3>{title}</h3><span className="pill purple">만세력 계산</span></div>{chart.solarDate&&<p className="converted-date">양력 {chart.solarDate} · 음력 {chart.lunarDate}{chart.leap?' (윤달)':''}</p>}<div className="pillars-grid">{chart.pillars.map(p=><div className={p.label==='일주'?'pillar day-pillar':'pillar'} key={p.label}><small>{p.label}</small>{p.value?<><strong className={`element-${stemInfo(p.value[0]).elementIndex}`}>{p.value[0]}<br/>{p.value[1]}</strong><span>{p.korean}</span></>:p.unknown?<><strong className="unknown-pillar">?</strong><span>시간 미상</span></>:<><div className="pillar-candidates">{p.candidates.map(v=><b key={v}>{v}</b>)}</div><span>시간 확인</span></>}</div>)}</div><div className="elements-heading"><h4>원국의 오행</h4><small>{chart.unknown?'시주 제외 · ':''}천간 + 지지 대표 오행</small></div><div className="elements-grid">{chart.elements.map((e,i)=><div key={e.name} className={`element-count element-${i}`}><span>{e.name}</span><strong>{countLabel(e)}<small>개</small></strong><div className="element-track"><i style={{width:`${e.max/8*100}%`}}/></div></div>)}</div><p className="element-caption">가중치 없이 센 개수예요. 오행의 강약·용신을 판정한 값은 아니에요.</p>{chart.warnings.map(w=><p className="chart-warning" key={w}>{w}</p>)}<details className="chart-basis"><summary>계산 기준과 자료 보기 <ChevronDown size={15}/></summary><p>한국 표준시(UTC+9) · 년주는 입춘, 월주는 절입 시각 기준 · 일주 경계는 {chart.boundary==='zi'?'밤 23:00':'자정 00:00'} · 시주는 2시간 단위예요.</p><p>출생지에 따른 태양시, 과거 표준시·서머타임은 자동 보정하지 않아요. 해당 출생 정보는 표준시로 보정해 입력해주세요. 절기 시각은 계산값이며 경계에 매우 가까우면 다른 역서와 차이가 날 수 있어요.</p><p><a href="https://astro.kasi.re.kr/kor/life/post/calendarData?search_year=2026" target="_blank" rel="noreferrer">한국천문연구원 달력 자료</a> · <a href="https://github.com/usingsky/korean_lunar_calendar_js" target="_blank" rel="noreferrer">한국 음력 데이터</a> · <a href="https://github.com/6tail/lunar-javascript" target="_blank" rel="noreferrer">절기 계산 자료</a></p></details></section>;
}
function Modal({ children, title, onClose, wide = false }) { const ref=useRef(); useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close();},[]);return <dialog ref={ref} role="dialog" aria-modal="true" className={`modal ${wide?'wide':''}`} aria-label={title} onCancel={onClose} onClose={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-header"><span>{title}</span><button className="icon-button" aria-label="닫기" onClick={onClose}><X size={21}/></button></div>{children}</dialog>; }
function Toast({message}){const ref=useRef();useEffect(()=>{ref.current?.showPopover?.();},[message]);return <div ref={ref} popover="manual" className="toast" role="status"><Check size={16}/>{message}</div>;}

function App({vault}) {
  const [me,setMe]=useState(blankPerson),[other,setOther]=useState(blankPerson),[relation,setRelation]=useState('연인'),[modal,setModal]=useState(null),[result,setResult]=useState(null),[toast,setToast]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mobileMenu,setMobileMenu]=useState(false),[info,setInfo]=useState('');
  const [cardPreview,setCardPreview]=useState('');
  const saved=vault.data.results, setSaved=vault.setResults;
  const charmAlbum=vault.charms;
  const [collectionBack,setCollectionBack]=useState(null);
  function openCollection(back=null){setCollectionBack(back);open('collection');}
  const toastTimer=useRef(), busyTimer=useRef();const today=seoulDate();const dateText=new Date(`${today}T12:00:00+09:00`).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'long'});
  function notify(message){setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3500);}
  useEffect(()=>{function readShare(){const shared=parseSharedCard(location.hash);if(shared){setResult(shared);setModal('result');}}readShare();window.addEventListener('hashchange',readShare);return()=>{window.removeEventListener('hashchange',readShare);clearTimeout(toastTimer.current);clearTimeout(busyTimer.current);};},[]);
  useEffect(()=>{if(location.hash==='#account')setModal('account');},[]);
  function open(type){setError('');setModal(type);setMobileMenu(false);}
  function scrollTo(id){document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});setMobileMenu(false);}
  function generate(e,kind){e.preventDefault();const problem=validatePerson(me) || (kind==='match'?validatePerson(other):'');if(problem){setError(problem);return;}setError('');setBusy(true);busyTimer.current=setTimeout(()=>{try{setResult(kind==='match'?makeCompatibility(me,other,relation):makeFortune(me,kind));setModal('result');}catch(e){setError(e.message || '계산을 완료하지 못했어요. 입력을 확인해주세요.');}finally{setBusy(false);}},750);}
  function continueToSaju(){const next=makeSajuFromResult(result);if(!next){open('saju');return;}setError('');setResult(saved.find(r=>r.id===next.id)||next);setModal('result');}
  function saveResult(){if(saved.some(x=>x.id===result.id)){notify('이미 내 운세 서랍에 담겨 있어요.');return;}setSaved([savedResult(result),...saved].slice(0,20));notify('내 운세 서랍에 소중히 담았어요.');}
  function unlock(){setResult({...result,unlocked:true});setSaved(saved.map(r=>r.id===result.id?{...r,unlocked:true}:r));setModal('result');notify('상세 풀이를 열었어요. 실제 결제는 발생하지 않았어요.');}
  async function download(share=false){setBusy(true);try{const {blob,preview}=await createCard(result);const file=new File([blob],'몽글사주-결과카드.png',{type:'image/png'});if(share && navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'몽글사주',text:`몽글도사가 읽어준 내 이야기 · ${result.character?.name || result.headline || result.title} 🐹`});}else{setCardPreview(preview);setModal('card');}}catch(e){if(e.name!=='AbortError')notify('이미지를 만들지 못했어요. 다시 시도해주세요.');}finally{setBusy(false);}}
  async function copyLink(){const url=`${location.origin}${location.pathname}#card=${encodeURIComponent(JSON.stringify(publicCard(result)))}`;try{await navigator.clipboard.writeText(url);notify('결과 링크를 복사했어요. 생년월일은 포함되지 않아요.');}catch{setInfo(url);setModal('link');}}
  function updateReport(key,value){setResult(r=>({...r,[key]:value}));setSaved(list=>list.map(r=>r.id===result.id?{...r,[key]:value}:r));}
  const isSaved=result && saved.some(x=>x.id===result.id);
  const isPremium=result?.kind==='saju'&&result.unlocked&&!result.shared&&result.engine===ENGINE&&!!result.chart?.dayMaster;
  return <>
    <header className="header"><div className="header-inner"><a className="brand" href="#" aria-label="몽글사주 홈"><Hamster size={42}/><span>몽글사주<small>MONGLE SAJU</small></span></a><nav aria-label="주 메뉴" className={mobileMenu?'nav expanded':'nav'}><button onClick={()=>scrollTo('today')}>오늘의 운세 <span className="nav-free">FREE</span></button><button onClick={()=>open('saju')}>나의 사주</button><button onClick={()=>open('match')}>우리의 궁합</button><button onClick={()=>scrollTo('about')}>몽글도사 이야기</button></nav><button className="account-entry" onClick={()=>open('account')}>{vault.session?.user?'내 계정':'로그인'}</button><button className="saved-button" aria-label="내 운세 서랍" onClick={()=>open('saved')}><Bookmark size={16}/><span>내 운세 서랍</span>{saved.length>0&&<b>{saved.length}</b>}</button><button className="mobile-menu icon-button" aria-label="메뉴 열기" aria-expanded={mobileMenu} onClick={()=>setMobileMenu(!mobileMenu)}>{mobileMenu?<X/>:<Menu/>}</button></div></header>
    <main>
      <section className="hero section-wrap"><div className="hero-copy"><div className="eyebrow"><span className="little-star">✦</span> 작은 햄스터가 건네는 큰 위로</div><h1>오늘도,<br/>좋은 운이 <span>올 거예요.<svg viewBox="0 0 250 15" preserveAspectRatio="none"><path d="M3 10Q110 0 247 7" fill="none" stroke="#eac1ad" strokeWidth="8" strokeLinecap="round"/></svg></span></h1><p>조금 궁금한 내일, 조금 복잡한 마음.<br/>몽글도사와 함께 가볍게 들여다봐요.</p><button className="button primary hero-cta" onClick={()=>scrollTo('today')}><Sparkles size={17}/> 오늘의 운세 무료로 보기 <ArrowRight size={17}/></button><div className="hero-footnote"><span className="tiny-dot"/> 가입 없이, 부담 없이, 몽글하게</div></div><div className="hero-art"><div className="art-orbit"/><div className="floating-label open-label"><span/> 몽글도사 영업 중</div><span className="hero-spark s1">✦</span><span className="hero-spark s2">✧</span><img className="hamster-hero" src="/hamster.png" alt="라벤더 마법사 모자를 쓰고 수정구슬을 보는 귀여운 햄스터 몽글도사"/><div className="hero-speech"><span>“</span>너의 내일에, 작은 행운 한 알.<Heart size={13}/></div><div className="seed-tag">해바라기씨로 보는 마음의 별자리</div></div></section>
      <div className="intro-strip section-wrap"><span>마음이 향하는 곳부터 시작해요</span><span><Flower2 size={15}/> 오늘도 당신 편, 몽글도사</span></div>
      <section className="services section-wrap" aria-label="운세 서비스"><button className="service-card daily-card" onClick={()=>scrollTo('today')}><div className="service-top"><span className="pill green">매일 무료</span><ArrowUpRight size={21}/></div><div className="service-content"><div><h2>오늘의 운세</h2><p>하루를 시작하는 작은 힌트</p><span className="service-bottom">오늘의 행운 만나기 <ArrowRight size={14}/></span></div><MiniArt type="sun"/></div></button><button className="service-card saju-card" onClick={()=>open('saju')}><div className="service-top"><span className="pill purple">몽글한 깊이</span><ArrowUpRight size={21}/></div><div className="service-content"><div><h2>나의 사주</h2><p>나도 몰랐던, 나다운 이야기</p><span className="service-bottom">상세 풀이 <strong>990원</strong><span className="demo-mini">DEMO</span></span></div><MiniArt type="orb"/></div></button><button className="service-card match-card" onClick={()=>open('match')}><div className="service-top"><span className="pill pink">연인 · 친구 · 전 애인</span><ArrowUpRight size={21}/></div><div className="service-content"><div><h2>우리의 궁합</h2><p>우리는 어떤 온도의 사이일까?</p><span className="service-bottom">마음의 거리 알아보기 <ArrowRight size={14}/></span></div><MiniArt type="heart"/></div></button></section>
      <GuardianShowcase onStart={()=>open('saju')} collection={charmAlbum.collection} onOpenCollection={()=>openCollection()}/>
      <section id="today" className="today-section section-wrap"><div className="section-heading"><div><div className="eyebrow">DAILY LITTLE LUCK</div><h2>오늘, 나에게 온 행운 <Sparkles size={25}/></h2><p>몽글도사가 당신만을 위한 하루의 힌트를 준비했어요.</p></div><span className="date-chip"><Sun size={15}/>{dateText}</span></div><div className="today-grid"><div className="today-story"><div className="story-top"><span className="pill paper">몽글도사의 한마디</span><span>✦</span></div><h3>모든 날이 반짝이지 않아도,<br/>당신은 충분히 빛나고 있어요.</h3><p>잘될 거라는 작은 믿음 하나.<br/>오늘은 그걸 주머니에 쏙 넣어두세요.</p><div className="story-drawing"><div className="draw-moon"/><span className="draw-star ds1">✧</span><span className="draw-star ds2">✦</span><div className="story-hamster"><Hamster size={128}/></div><div className="draw-cloud dc1"/><div className="draw-cloud dc2"/></div><div className="story-footer"><span>몽글몽글, 좋은 일이 생길지도</span><Heart size={14}/></div></div><form className="today-form" onSubmit={e=>generate(e,'daily')}><div className="form-intro"><h3>당신의 이야기를 들려주세요</h3><span>FREE</span></div><p className="form-subtitle">태어난 순간에 숨어 있는 작은 힌트</p><PersonFields value={me} setValue={setMe}/>{error&&modal===null&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="button primary form-submit"><Sparkles size={17}/>{busy?'몽글도사가 별을 읽고 있어요…':'나의 무료 운세 받아보기'}<ArrowRight size={17}/></button><p className="privacy-note"><LockKeyhole size={12}/> 생년월일은 서버로 전송하거나 저장하지 않아요.</p></form></div></section>
      <section id="match" className="relationship-section section-wrap"><div className="relation-copy"><span className="eyebrow">A LITTLE CLOSER</span><h2>우리 사이에도<br/>몽글한 이유가 있을까요?</h2><p>설레는 연인, 편안한 친구, 문득 떠오른 그 사람.<br/>서로의 마음을 알아가는 작은 시간을 가져보세요.</p><div className="relation-tabs">{['연인','친구','전 애인'].map(t=><button key={t} onClick={()=>setRelation(t)} aria-pressed={relation===t} className={relation===t?'selected':''}>{t==='연인'?'♡':t==='친구'?'✿':'☾'} {t}</button>)}</div><button className="text-button" onClick={()=>open('match')}>우리의 궁합 보러 가기 <ArrowRight size={18}/></button></div><div className="match-visual"><div className="mini-result r-left"><span>나의 마음</span><Hamster size={83}/><strong>다정한 햇살형</strong><small>따뜻함을 나누는 사람</small></div><div className="match-center"><Heart size={26} fill="#eaa29b"/><span>서로를 알아가는 시간</span><span className="sample-label">예시 카드</span></div><div className="mini-result r-right"><span>너의 마음</span><div className="pink-hamster"><Hamster size={83}/></div><strong>포근한 달빛형</strong><small>조용히 곁을 지키는 사람</small></div></div></section>
      <section className="share-section section-wrap"><div className="share-visual"><div className="sample-card"><span className="sample-card-brand">✦ 몽글사주 ✦</span><Hamster size={78}/><small>오늘의 나는</small><strong>큰 나무처럼 자라는 마음</strong><div><span>甲</span>목</div><p>내 일간을 귀여운 카드 한 장에</p><span className="sample-card-foot">#나의사주 #몽글사주 · 예시</span></div><div className="share-sticker">행운 배달 왔어요!<Heart size={15}/></div><span className="share-doodle">✧</span></div><div className="share-copy"><div className="eyebrow">GOOD LUCK, TOGETHER</div><h2>좋은 운은,<br/>나누면 더 커지니까.</h2><p>내 운세를 귀여운 카드 한 장에 담아보세요.<br/>친구에게 톡, 스토리에 쏙. 오늘의 행운을 나눠요.</p><div className="share-features"><span><Download size={15}/> 이미지로 저장</span><span><Share2 size={15}/> SNS로 공유</span></div><button className="button secondary" onClick={()=>scrollTo('today')}>나만의 행운 카드 만들기 <ArrowUpRight size={17}/></button></div></section>
      <section id="about" className="about-section section-wrap"><div className="about-avatar"><Hamster size={74}/></div><div><span className="eyebrow">MEET YOUR LITTLE FORTUNE TELLER</span><h2>안녕, 나는 몽글도사예요.</h2><p>해바라기씨를 좋아하고, 당신의 이야기는 더 좋아해요.<br/>정답을 알려주기보다 마음이 조금 가벼워지는 시간을 선물하고 싶어요.</p></div><span className="about-star">✦</span></section>
      <section className="faq section-wrap"><h2>조금 더 궁금한 이야기</h2>{[['정말 무료로 볼 수 있나요?','오늘의 운세와 궁합 체험은 무료예요. 상세 사주의 990원 해금도 현재는 데모라 실제 결제가 발생하지 않아요.'],['태어난 시간을 몰라도 괜찮나요?','네! 시주를 제외하고 계산해요. 절기나 일주 경계가 있는 날에는 하나로 추측하지 않고 가능한 원국을 표시해요.'],['입력한 정보는 어디에 저장되나요?','생년월일시와 달력 선택은 현재 화면에서만 사용해요. ‘운세 담기’를 누르면 이름·사주 글자·풀이·선택한 상황과 실천 체크·선택한 부적이 비회원이면 이 브라우저에, 로그인하면 계정에 저장돼요. 입력한 생년월일시는 보관하지 않아요. 내 운세 서랍에서 삭제할 수 있어요.'],['결과 카드는 어떻게 공유하나요?','결과 화면에서 PNG 이미지로 저장하거나 SNS 공유를 선택하세요. 지원되는 모바일에서는 공유 메뉴가 열리고, 그 외에는 이미지로 저장돼요. 결과 링크에는 표시 이름과 운세 요약이 포함돼요.']].map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</section>
    </main>
    <footer className="footer section-wrap"><div className="footer-top"><a className="brand" href="#"><Hamster size={34}/><span>몽글사주</span></a><div><button onClick={()=>{setInfo('terms');open('info');}}>이용 안내</button><button onClick={()=>{setInfo('privacy');open('info');}}>개인정보 안내</button><span className="footer-demo">결제 DEMO</span></div></div><p>운세는 하루를 조금 즐겁게 만드는 이야기예요. 당신의 선택과 가능성은 언제나 당신에게 있어요.</p><div className="footer-bottom"><span>© {today.slice(0,4)} MONGLE SAJU. Made with a little luck.</span><span>한국 음력 · 절기 기준 원국 계산 · 결제는 데모</span></div></footer>
    <nav className="bottom-nav" aria-label="모바일 빠른 메뉴"><button onClick={()=>scrollTo('today')}><Sun size={19}/>오늘의 운세</button><button onClick={()=>open('saju')}><Sparkles size={19}/>나의 사주</button><button onClick={()=>open('match')}><Heart size={19}/>궁합</button><button onClick={()=>open('saved')}><Bookmark size={19}/>내 운세</button></nav>
    {toast&&<Toast message={toast}/>}
    {modal==='account'&&<Modal title="로그인 · 내 계정" onClose={()=>{setModal(null);if(location.hash==='#account')history.replaceState(null,'',location.pathname);}}><div className="modal-body"><AccountPanel vault={vault}/></div></Modal>}
    {vault.error&&<div className="vault-status" role="alert">{vault.error}<button onClick={()=>open('account')}>계정 확인</button></div>}
    {(modal==='saju'||modal==='match')&&<Modal title={modal==='saju'?'나의 사주 이야기':'우리의 궁합'} onClose={()=>setModal(null)}><form onSubmit={e=>generate(e,modal)} className="modal-body"><div className="modal-mascot"><Hamster size={62}/></div><h2>{modal==='saju'?'당신은 어떤 별을 품고 있나요?':`${relation}, 우리 마음의 온도는?`}</h2><p className="modal-subtitle">{modal==='saju'?'기본 풀이를 먼저 만나고, 상세 이야기를 열어보세요.':'두 사람의 이야기를 몽글하게 들여다봐요.'}</p>{modal==='match'&&<div className="relation-tabs centered">{['연인','친구','전 애인'].map(t=><button type="button" key={t} onClick={()=>setRelation(t)} aria-pressed={relation===t} className={relation===t?'selected':''}>{t}</button>)}</div>}<h3 className="person-title">{modal==='match'?'나의 정보':'나의 탄생 정보'}</h3><PersonFields prefix="modal-me" value={me} setValue={setMe}/>{modal==='match'&&<><h3 className="person-title second">상대방의 정보</h3><PersonFields prefix="other" value={other} setValue={setOther}/></>}{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}><WandSparkles size={17}/>{busy?'몽글도사가 별을 읽고 있어요…':modal==='match'?'우리의 궁합 만나보기':'나의 사주 만나보기'}</button><p className="privacy-note">한국 음력·절기 기준 계산 · 해석은 참고용</p></form></Modal>}
    {modal==='result'&&result&&<Modal key={result.id} title={result.shared?'공유받은 행운 카드':result.kind==='match'?'우리의 궁합 결과':result.kind==='saju'?'나의 사주 결과':'오늘의 무료 운세'} onClose={()=>{setModal(null);if(location.hash.startsWith('#card='))history.replaceState(null,'',location.pathname+location.search);}} wide><div className="modal-body result-body">{!isPremium&&<div className="result-intro"><span className="pill purple">{result.date} · {result.kind==='match'?`${result.relation} 궁합`:'몽글한 하루'}</span><Hamster size={88}/><p>{result.name}님의 {result.kind==='match'?'마음 온도':'작은 행운'}</p><div className={`result-score ${result.engine?'calculated-headline':''}`}>{result.engine?result.headline:<>{result.score}<span>점</span></>}<Sparkles size={23}/></div>{result.engine&&<p className="result-subline">{result.subline}</p>}<h2>{result.title}</h2><p className="result-description">{result.description}</p></div>}
{result.kind==='saju'&&!result.shared&&result.engine===ENGINE&&(isPremium?<PremiumReport result={result} onChecksChange={v=>updateReport('reportChecks',v)} onContextChange={v=>updateReport('storyContext',v)} onGuardChange={v=>updateReport('guardKey',v)} onBless={v=>updateReport('guardBlessedKey',v)} collection={charmAlbum.collection} onCollect={charmAlbum.collect} onOpenCollection={()=>openCollection('result')} onAudienceChange={v=>updateReport('manualAudience',v)}/>: <ReportPreview result={result} onUnlock={()=>open('pay')} onGuardChange={v=>updateReport('guardKey',v)}/>)}
{result.kind==='match'&&!result.shared&&<MatchScenes result={result}/>}
{result.dailyScenes&&!result.shared&&<section className="daily-scenes"><h3><Sun size={18}/> 오늘의 장면 카드</h3>{result.dailyScenes.map((scene,i)=><article key={i}><b>{scene.title}</b><p>{scene.text}</p></article>)}</section>}
{result.engine?<><ChartPanel chart={result.chart} title="나의 사주 원국"/>{result.otherChart&&<ChartPanel chart={result.otherChart} title="상대방의 사주 원국"/>}{result.evidence&&<div className="reading-evidence"><h3><Sparkles size={17}/> 이렇게 읽었어요</h3>{result.evidence.map((text,i)=><p key={i}>{text}</p>)}</div>}{result.shared&&<p className="field-note">공유받은 요약 카드예요. 출생 정보가 없어 원국을 다시 계산하거나 검증하지 않아요.</p>}</>:<p className="legacy-note">이전 버전의 데모 결과예요. 실제 사주 계산 결과를 보려면 다시 입력해주세요.</p>}<div className="lucky-grid"><div><Flower2 size={19}/><small>나를 닮은 색</small><strong>{result.color}</strong></div><div><Coffee size={19}/><small>일상의 작은 아이템</small><strong>{result.item}</strong></div></div><div className="mission"><Star size={20}/><div><small>몽글도사의 오늘 미션</small><strong>{result.action}</strong></div></div><div className="result-actions"><button className="button secondary" onClick={saveResult}><Bookmark size={16} fill={isSaved?'currentColor':'none'}/>{isSaved?'담은 운세':'운세 담기'}</button><button disabled={busy} className="button secondary" onClick={()=>download()}><Download size={16}/>카드 저장</button></div><div className="result-actions"><button disabled={busy} className="button primary" onClick={()=>download(true)}><Share2 size={16}/>SNS 공유</button><button className="button secondary" onClick={copyLink}><Link size={16}/>링크 복사</button></div><p className="privacy-note">공유 카드에는 이름과 결과가 포함돼요. 생년월일은 포함되지 않아요.</p>{['daily','match'].includes(result.kind)&&<section className="result-next" aria-label="나의 사주 이어보기"><span>{result.kind==='match'?'궁합 다음에는, 나의 사주':'오늘의 운세 다음에는, 나의 사주'}</span><h3>{result.kind==='match'?'우리의 궁합을 봤다면, 내 타입도 확인하세요.':'오늘의 흐름을 봤다면, 내 강점도 확인하세요.'}</h3><p>{result.shared?'내 탄생 정보를 입력하고 성격·직업·금전·연애 풀이를 만나보세요.':'방금 확인한 내 정보로 성격·직업·금전·연애 풀이까지 이어집니다.'}</p><button type="button" className="button primary full" onClick={continueToSaju}><WandSparkles size={18}/>나의 사주 바로 보기<ArrowRight size={18}/></button><small>기본 풀이 무료 · 상세 리포트 990원 데모</small></section>}<p className="result-disclaimer">원국·음력·십성은 표시한 기준에 따라 계산해요.<br/>풀이는 전통의 상징을 설명하는 참고 정보이며, 미래의 적중이나 관계의 성공을 보장하지 않아요.</p></div></Modal>}
    {modal==='pay'&&<Modal title="상세 사주 해금" onClose={()=>setModal('result')}><div className="modal-body payment-body"><div className="modal-mascot"><Hamster size={84}/></div><span className="pill purple">DEMO · 체험용 결제</span><h2>더 깊은 이야기를 열어볼까요?</h2><p>몽글도사가 준비한 열네 가지 이야기</p><ul>{['나의 햄스터 캐릭터와 강점·에너지 패턴','일의 방식과 직무 예시 3가지','취업·회사·이직 등 상황별 이야기','회사에서 꺼내볼 대화 문장','금전운·재물운 · 수입과 소비, 모으고 지키는 습관','연애운 · 솔로·커플·지난 인연의 대화','가정운·건강운 · 관계와 생활의 리듬','나와 닮은 반려동물 친구와 돌봄 체크','태어난 계절과 오행 이야기','체크하며 해보는 7일 실험','부적 10종 · 수집 도감 · 세트 완성 배지','친구·연인·동료용 나의 사용설명서 카드 3종'].map(t=><li key={t}><Check size={17}/>{t}</li>)}</ul><ManualPreview report={result?.chart?makeReport(result.chart):result?.report} compact/><GuardianCharm chart={result?.chart} selectedKey={result?.guardKey} compact/><div className="payment-total"><span>상세 사주 1회</span><strong>990<span>원</span></strong></div><div className="payment-note">현재는 데모예요.<br/>카드 정보 입력과 실제 청구 없이 해금됩니다.</div><button className="button primary full" onClick={unlock}>결제 없이 데모 해금하기 <ArrowRight size={17}/></button><button className="text-button centered" onClick={()=>setModal('result')}>다음에 볼게요</button></div></Modal>}
    {modal==='collection'&&<Modal title="나의 부적 도감" onClose={()=>setModal(collectionBack)} wide><div className="modal-body"><CharmCollection collection={charmAlbum.collection} onFavorite={charmAlbum.favorite} onRemove={charmAlbum.remove} onExplore={()=>open('saju')} storageError={charmAlbum.storageError} accountStorage={!!vault.session?.user}/></div></Modal>}
    {modal==='saved'&&<Modal title="내 운세 서랍" onClose={()=>setModal(null)}><div className="modal-body"><h2>소중히 모아둔 작은 행운</h2><p className="modal-subtitle">{vault.session?.user?'계정에 저장된 결과예요.':'이 브라우저에 저장된 결과예요.'} 최근 20개까지 담을 수 있어요.</p><div className="vault-status"><span role="status">{vault.status}</span><button onClick={()=>open('account')}>{vault.session?.user?'계정 관리':'로그인하고 보관하기'}</button></div><button type="button" className="album-entry" onClick={()=>openCollection('saved')}>나의 부적 도감 <b>{charmAlbum.collection.owned.length} / 10</b></button>{saved.length===0?<div className="empty"><Hamster size={88}/><h3>아직 서랍이 비어 있어요</h3><p>마음에 든 결과에서 ‘운세 담기’를 눌러주세요.</p><button className="button primary" onClick={()=>{setModal(null);scrollTo('today');}}>오늘의 행운 만나기</button></div>:<div className="saved-list">{saved.map(r=><div className="saved-row" key={r.id}><button onClick={()=>{setResult(r);setModal('result');}}><span>{r.kind==='match'?'♡':'✦'}</span><div><small>{r.date} · {r.name}</small><strong>{r.title}</strong></div><b>{r.headline || r.score}</b><ChevronRight size={16}/></button><button className="icon-button" aria-label={`${r.name}의 ${r.date} 운세 삭제`} onClick={()=>{setSaved(saved.filter(x=>x.id!==r.id));notify('운세를 서랍에서 꺼냈어요.');}}><X size={16}/></button></div>)}</div>}</div></Modal>}
    {modal==='info'&&<Modal title={info==='privacy'?'개인정보 안내':'이용 안내'} onClose={()=>setModal(null)}><div className="modal-body info-body"><h2>{info==='privacy'?'당신의 이야기를 소중히 다뤄요':'몽글사주를 즐기는 방법'}</h2>{info==='privacy'?<><p>입력한 생년월일시와 달력 종류는 브라우저 메모리에서 계산하며 서버로 전송하지 않아요. 로그인 시 로그인 서비스의 식별번호와 표시 이름을 서버에 보관해요. 이메일과 전화번호는 수집하지 않아요.</p><p>‘운세 담기’를 누르면 닉네임, 사주 글자와 오행, 풀이, 선택한 상황과 실천 체크, 선택한 부적이 비회원일 때는 현재 브라우저에, 로그인했을 때는 계정별 서버 보관함에 남아요. 입력한 생년월일시와 변환한 음양력 날짜는 보관하지 않아요. 내 운세 서랍에서 개별 삭제할 수 있어요.</p><p>로그인 후 계정 화면에서 비회원 보관함을 가져올 수 있고, 계정과 서버 보관 데이터를 삭제할 수 있어요. 부적 도감에는 모은 부적과 대표 부적을 운세와 같은 저장 위치에 보관해요. 도감에서 부적을 뺄 수 있어요. 공유 링크와 이미지에는 이름·해석 요약이 포함돼요. 사주 원국과 생년월일시는 포함하지 않아요. 공유할 때 공개해도 괜찮은 닉네임을 사용해주세요.</p></>:<><p>한국 음력 변환과 절기 기준의 사주 원국, 오늘의 십성, 연인·친구·전 애인 일간·일지 비교를 제공해요.</p><p>990원 상세 해금은 실제 결제 없이 동작해요. 한국 표준시(UTC+9) 입력을 기준으로 입춘에서 년주, 절입 시각에서 월주를 바꿔요. 일주는 자정 또는 밤 11시 기준을 선택할 수 있어요. 출생지의 태양시, 과거 표준시와 서머타임은 자동 보정하지 않아요.</p><p>결과 카드를 PNG로 저장하고 SNS에 공유해보세요. 운세는 재미로 읽고, 일상의 선택은 자신의 마음에 따라 해주세요.</p></>}</div></Modal>}
    {modal==='link'&&<Modal title="공유 링크" onClose={()=>setModal('result')}><div className="modal-body"><p>아래 링크를 길게 누르거나 선택해서 복사해주세요.</p><textarea readOnly className="link-text" value={info} onFocus={e=>e.target.select()}/></div></Modal>}
    {modal==='card'&&<Modal title="나만의 행운 카드" onClose={()=>setModal('result')}><div className="modal-body card-export"><img src={cardPreview} alt="SNS에 공유할 몽글사주 결과 카드"/><a className="button primary full" href={cardPreview} download="몽글사주-결과카드.png"><Download size={17}/>PNG 이미지 저장</a><p>1080 × 1350 · 인스타그램 피드에 맞는 카드예요.<br/>모바일에서는 이미지를 길게 눌러 저장할 수도 있어요.</p><button className="text-button centered" onClick={()=>setModal('result')}>운세 결과로 돌아가기 <ArrowRight size={15}/></button></div></Modal>}
  </>;
}
function Root(){const vault=useAccountVault();return vault.ready?<App key={vault.session?.user?.id||'guest'} vault={vault}/>:<main className="account-loading"><Hamster size={80}/><h1>몽글 보관함</h1><p role="status">{vault.error||'보관함을 확인하고 있어요…'}</p>{vault.error&&<button className="button primary" onClick={()=>location.reload()}>다시 연결하기</button>}</main>;}
createRoot(document.getElementById('root')).render(<Root/>);
