import React, { useState } from 'react';
import { Sparkles, ChevronDown, Check, ArrowRight, BookOpen, BriefcaseBusiness, Heart, MessageCircle, Sun, Leaf, CheckCheck, LockKeyhole, ShieldCheck, Wallet, Coins, House, Activity, PawPrint } from 'lucide-react';
import { makeReport, makeMatchStory } from './report.js';
import './report.css';
import {GuardianCharm} from './GuardianCharm.jsx';
import {ManualPreview,ManualCard} from './ManualCard.jsx';
import './reader.css';
import {makeStoryDetails} from './storyDetails.js';
import {StoryText,StoryHook,StoryExamples} from './StoryExamples.jsx';
import {makeLifeReadings} from './lifeReadings.js';
import {LifeChapter} from './LifeChapter.jsx';

const chapters=[['self','나의 성격과 핵심 타입',BookOpen],['manual','나를 대하는 사용설명서',MessageCircle],['career','직업운 · 강점이 드러나는 일',BriefcaseBusiness],['office','회사에서의 대화법',MessageCircle],['money','금전운 · 버는 돈과 쓰는 돈',Wallet],['wealth','재물운 · 모으고 지키는 힘',Coins],['love','연애운 · 마음이 만나는 방식',Heart],['family','가정운 · 함께 사는 마음',House],['health','건강운 · 나를 돌보는 리듬',Activity],['pets','어울리는 반려동물 친구',PawPrint],['daily','선택과 일상의 습관',Sun],['season','계절이 더하는 성향',Leaf],['guardian','몽글도사의 액운막기',ShieldCheck],['practice','나를 위한 7일 실험',CheckCheck]];
function CharacterArt({character,className=''}) {
  return <img className={`report-art ${className}`} src={character?.image || '/hamster.png'} alt={character?.alt || '몽글도사 햄스터'} loading="lazy"/>;
}
function Quote({children}) {return <blockquote className="report-quote"><MessageCircle size={15}/><p>“{children}”</p></blockquote>;}
function ReportChapter({id,index,title,Icon,children,open=false}) {
  return <details className="report-chapter" open={open} id={`report-${id}`}><summary><span className="chapter-number">{String(index+1).padStart(2,'0')}</span><Icon size={17}/><h4>{title}</h4><ChevronDown size={17} className="chapter-chevron"/></summary><div className="chapter-content">{children}</div></details>;
}
export function ReportPreview({result,onUnlock,onGuardChange}) {
  const report=result.chart ? makeReport(result.chart) : result.report;
  if(!report)return null;
  if(report.uncertain)return <div className="report-uncertain"><Sparkles size={24}/><h3>{report.title}</h3><p>{report.note}</p><p>이 상태에서는 상세 해금을 권하지 않아요. 입력창에서 출생 시각이나 날짜 경계 기준을 먼저 확인해주세요.</p></div>;
  return <section className="report-preview"><div className="preview-character"><CharacterArt character={report.character}/><div><span className="report-eyebrow">YOUR LITTLE CHARACTER</span><h3>{report.character.name}</h3><p>{report.character.tagline}</p></div></div><p className="preview-hook">사주 글자 다음에는,<br/><strong>당신의 타입과 강점을 짚어드립니다.</strong></p><div className="preview-value"><span><BriefcaseBusiness size={16}/> 직무 예시 3가지</span><span><MessageCircle size={16}/> 상황별 대화 문장</span><span><Heart size={16}/> 금전·재물·연애·가정·건강운</span><span><CheckCheck size={16}/> 직접 해보는 7일 실험</span></div><div className="preview-pages">{chapters.map(([id,title],i)=><span key={id}><b>{String(i+1).padStart(2,'0')}</b>{title}{i>1&&<LockKeyhole size={10}/>}</span>)}</div><ManualPreview report={report}/><GuardianCharm chart={result.chart} selectedKey={result.guardKey} onSelect={onGuardChange}/><button className="button primary full" onClick={onUnlock}>990원 나의 사주 리포트 열기 <span className="button-tag">데모</span><ArrowRight size={16}/></button><small className="preview-payment-note">지금은 실제 결제 없이 열네 가지 이야기와 부적 10종을 모두 읽어요.</small></section>;
}
export function PremiumReport({result,onChecksChange,onContextChange,onGuardChange,onBless,collection,onCollect,onOpenCollection,onAudienceChange}) {
  const report=result.chart ? makeReport(result.chart) : result.report;
  const [context,setContext]=useState(result.storyContext || 'working');
  const [largeText,setLargeText]=useState(false);
  function jump(id){const el=document.getElementById('report-'+id);if(el){el.open=true;el.querySelector('summary')?.focus({preventScroll:true});el.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});}}
  function expandAll(open){chapters.forEach(([id])=>{const el=document.getElementById('report-'+id);if(el)el.open=open;});}
  if(!report || report.uncertain)return <ReportPreview result={result}/>;
  const stories=report.storyDetails || makeStoryDetails(result.chart,report.theme.id);
  const life=report.lifeReadings || makeLifeReadings(result.chart,report.theme);
  const selected=report.contexts.find(c=>c.id===context) || report.contexts[0];
  const checks=Array.isArray(result.reportChecks)?[...new Set(result.reportChecks.filter(n=>Number.isInteger(n)&&n>=1&&n<=7))]:[];
  function changeContext(value){setContext(value);onContextChange?.(value);}
  function toggle(day){onChecksChange?.(checks.includes(day)?checks.filter(x=>x!==day):[...checks,day]);}
  const content={
    manual:<ManualCard report={report} name={result.name} audience={result.manualAudience} onAudienceChange={onAudienceChange}/>,
    self:<><StoryHook>{stories?.hook}</StoryHook><StoryText className="chapter-lead" text={report.persona.intro}/><div className="strength-chips">{report.strengths.map(t=><span key={t}>✦ {t}</span>)}</div><div className="scene-pair"><div><span className="scene-label">가장 강한 부분</span><p>{report.persona.bright}</p></div><div><span className="scene-label">반복되기 쉬운 약점</span><p>{report.persona.shadow}</p></div></div><div className="report-action"><Leaf size={17}/><div><b>나를 편하게 만드는 작은 전환</b><p>{report.persona.reset}</p></div></div><StoryExamples items={stories?.self} title="일상에서 드러나는 특징"/><p className="report-caption">일간의 상징으로 풀이한 성향입니다. 아래의 생활 예시는 이 타입의 특징을 구체적으로 설명합니다.</p></>,
    career:<><StoryHook>{report.theme.hook}</StoryHook><div className="work-theme"><span>{report.theme.generic?'출생 시간 확인 전 · 일반 업무 예시':'원국에서 읽은 일의 테마'}</span><h5>{report.theme.label}</h5><p>{report.theme.hook}</p></div><p>이 업무 타입의 강점을 사용하는 직무는 다음과 같습니다. 각 직무에서 실제로 무엇을 하는지 하루 업무와 결과물로 설명합니다.</p><div className="career-card-list">{report.jobs.map((job,i)=><article className="career-card" key={job.title}><div className="career-card-title"><span>{String(i+1).padStart(2,'0')}</span><h5>{job.title}</h5></div><p>{job.task}</p><div className="career-scene"><span>이 일을 하는 하루</span><p>{job.scene}</p></div>{stories?.career?.[job.title]&&<ol className="career-day" aria-label={job.title+"의 하루 예시"}>{stories.career[job.title].map(step=><li key={step}>{step}</li>)}</ol>}<details className="job-connection"><summary>이 예시가 나온 이유 <ChevronDown size={12}/></summary><p>{job.connection}</p></details></article>)}</div><div className="context-picker"><label htmlFor="report-context">지금의 나는 어떤 상황인가요?</label><select id="report-context" value={context} onChange={e=>changeContext(e.target.value)}>{report.contexts.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></div><div className="context-story" aria-live="polite"><span className="scene-label">{selected.label} · 핵심 포인트</span><h5>{selected.title}</h5><StoryText text={selected.story}/><StoryText text={selected.personal}/><StoryExamples items={stories?.contexts?.[selected.id]} title={selected.label+"의 실제 상황"} label="지금 내 상황에 맞게"/><div className="report-action"><Sparkles size={16}/><div><b>오늘 해볼 행동</b><p>{selected.action}</p></div></div></div></>,
    office:<><StoryHook>{report.theme.hook}</StoryHook><h5>{report.office.title}</h5><StoryText text={report.office.story}/><Quote>{report.office.say}</Quote><div className="pattern-note"><b>이 순간에는 잠깐 멈춰보기</b><p>{report.office.watch}. 업무의 범위와 내가 원하는 역할을 실제 대화로 확인해보세요.</p></div><StoryExamples items={stories?.office} title="회의실에서 꺼내는 작은 대본" label="업무 상황별 예시"/></>,
    money:<LifeChapter reading={life?.money}/>,
    wealth:<LifeChapter reading={life?.wealth}/>,
    family:<LifeChapter reading={life?.family}/>,
    health:<LifeChapter reading={life?.health}/>,
    pets:<LifeChapter reading={life?.pets}/>,
    love:<LifeChapter reading={life?.love}><Quote>{report.love.say}</Quote><div className="pattern-note"><b>다정함과 함께 지킬 경계</b><p>{report.love.boundary}</p></div><StoryExamples items={stories?.love} title="답장·약속·서운함, 내 마음의 번역기" label="가까운 사이의 예시"/><p className="report-caption">상대의 성격을 추측하기보다, 실제로 겪은 일과 내 마음을 나누는 문장으로 써보세요.</p></LifeChapter>,
    daily:<><StoryHook>{stories?.dailyHook}</StoryHook><h5>{report.money.title}</h5><StoryText text={report.money.story}/><StoryExamples items={stories?.daily} title="작은 선택이 편해지는 연습"/><div className="report-action"><Sun size={17}/><div><b>나의 선택을 알아보는 작은 실험</b><p>{report.money.action}</p></div></div></>,
    season:<><h5>{report.season.title}</h5><StoryText text={report.season.story}/><div className="report-action"><Leaf size={17}/><div><b>계절의 상징을 하루에 옮긴다면</b><p>{report.season.action}</p></div></div><div className="pattern-note"><b>{report.balance.title}</b><StoryText text={report.balance.text}/></div>{stories?.seasonExample&&<StoryHook note={stories.seasonExample}>계절에서 읽는 실천 포인트</StoryHook>}</>,
    guardian:<GuardianCharm chart={result.chart} name={result.name} selectedKey={result.guardKey} onSelect={onGuardChange} full blessedKey={result.guardBlessedKey} onBless={onBless} collection={collection} onCollect={onCollect} onOpenCollection={onOpenCollection}/>,
    practice:<><p>일곱 날을 연속으로 지킬 필요는 없어요. 마음이 가는 행동부터 해보고 체크해보세요. 나에게 맞는 것만 사용설명서에 남겨도 충분해요.</p><div className="practice-progress"><span>{checks.length} / 7개의 작은 실험</span><b>{checks.length===7?'나만의 설명서를 완성했어요!':'하나씩, 내 속도로'}</b><div><i style={{width:`${checks.length/7*100}%`}}/></div></div><div className="practice-list">{report.plan.map(item=><label key={item.day} className={checks.includes(item.day)?'practice-item completed':'practice-item'}><input type="checkbox" checked={checks.includes(item.day)} onChange={()=>toggle(item.day)}/><span className="practice-check">{checks.includes(item.day)&&<Check size={14}/>}</span><div><small>DAY {item.day}</small><strong>{item.title}</strong><p>{item.action}</p></div></label>)}</div><p className="report-caption">‘운세 담기’를 누른 리포트의 체크 상태는 이 브라우저에 함께 보관돼요.</p></>
  };
  return <section className="premium-report" data-reader-size={largeText?"large":"normal"} aria-label="나의 상세 사주 리포트"><header className="report-cover readable-cover"><CharacterArt character={report.character}/><div><span className="report-eyebrow">MONGLE PERSONAL REPORT · 14 STORIES</span><h3>{result.name}님의 사주 리포트</h3><h4>{report.character.name}</h4><p>{report.character.tagline}</p><span className="character-stamp">{report.anchors[0]}</span></div></header><section className="report-summary" aria-label="사주 핵심 요약"><h3><Sparkles size={19}/> 먼저 읽는 핵심 3줄</h3><dl><div><dt>나의 타입</dt><dd>{report.persona.type} · {report.persona.tags.slice(0,2).join(" · ")}</dd></div><div><dt>일의 방식</dt><dd>{report.theme.work}</dd></div><div><dt>편해지는 습관</dt><dd>{report.persona.reset}</dd></div></dl></section><div className="reader-tools"><div role="group" aria-label="본문 글자 크기"><span>글자 크기</span><button type="button" aria-pressed={!largeText} onClick={()=>setLargeText(false)}>기본</button><button type="button" aria-pressed={largeText} onClick={()=>setLargeText(true)}>크게</button></div><div><button type="button" onClick={()=>expandAll(true)}>모두 펼치기</button><button type="button" onClick={()=>expandAll(false)}>모두 접기</button></div></div><nav className="report-toc" aria-label="상세 사주 목차">{chapters.map(([id,title],i)=><button type="button" key={id} onClick={()=>jump(id)}><span>{String(i+1).padStart(2,"0")}</span>{title}</button>)}</nav><div className="report-opening"><Sparkles size={18}/><p>성격·일·돈·관계의 핵심부터 짚습니다.<br/>타입 설명 다음에 구체적인 생활 예시가 이어집니다.</p></div>{chapters.map(([id,title,Icon],index)=><ReportChapter key={id} id={id} index={index} title={title} Icon={Icon} open={index===0}>{content[id]}</ReportChapter>)}<details className="report-method"><summary>내 리포트는 이렇게 만들었어요 <ChevronDown size={15}/></summary>{Object.values(report.basis).map((text,i)=><p key={i}>{text}</p>)}<p>캐릭터·장면·직무 예시는 전통의 상징을 일상으로 옮긴 창작 콘텐츠예요. 실제 성격·적성 검사나 미래 예측이 아니며, 직업의 선택은 내 역량·경험·관심과 함께 판단해주세요.</p></details><p className="report-endnote">내 타입의 강점은 분명하게,<br/>선택의 기준은 구체적으로. 몽글도사가 함께합니다. 🐹</p></section>;
}
export function MatchScenes({result}) {
  const story=result.matchStory || (result.chart&&result.otherChart&&makeMatchStory(result.chart,result.otherChart,result.relation));
  if(!story)return null;
  const names=result.name.split(' & ');
  return <section className="match-scenes"><div className="match-character-pair">{story.characters.map((c,i)=><div key={i}><CharacterArt character={c}/><small>{names[i] || (i?'상대방':'나')}</small><strong>{c.name}</strong></div>)}</div><h3><Heart size={17}/> 궁합에서 확인할 세 가지</h3><p className="report-caption">두 일간의 성향과 실제 대화 방식을 함께 풀이합니다.</p>{story.cards.map((card,i)=><details className="match-scene" key={i} open={i===0}><summary><span>0{i+1}</span><h4>{card.title}</h4><ChevronDown size={15}/></summary><div><p>{card.text}</p><Quote>{card.say}</Quote></div></details>)}</section>;
}
